Resources:
  TodoerSecurityGroup:
    DependsOn: TodoerVPC
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Todoer Functions
      VpcId:
        Ref: TodoerVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '0'
          ToPort: '65535'
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: 'Name'
          Value: 'TodoerSecurityGroup'
