Resources:
  TodoerVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: ${self:custom.DB.VPC_CIDR}.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: 'Name'
          Value: 'TodoerVPC'
