service:
  name: todo-api

plugins: ${file(../config.yml):plugins}

custom: ${file(../config.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: us-east-1
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-SharedGW-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-SharedGW-rootResourceId
  tracing:
    lambda: true

functions:
  create:
    handler: create.main
    events:
      - http:
          path: todos
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: get.main
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: list.main
    events:
      - http:
          path: todos
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: update.main
    events:
      - http:
          path: todos/{id}
          method: patch
          cors: true
          authorizer: aws_iam
  delete:
    handler: delete.main
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true
          authorizer: aws_iam
